### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by designbyjm** [Studio164a/jNewsticker-for-WordPress#1]
Hi Studio164a, 

We are experiencing a major error that actually took down a client website. See below...

PHP Fatal error: Uncaught Error: Function name must be a string in /www/wp-content/plugins/jnewsticker-for-wordpress/data_source.class.php:491
Stack trace:
#0 /www/wp-content/plugins/jnewsticker-for-wordpress/jnewsticker.class.php(589): jNewsticker_Data_Source->display_item(Object(WP_Post))
#1 /www/wp-content/plugins/jnewsticker-for-wordpress/jnewsticker-for-wordpress.php(351): jNewsticker->display(false)
#2 /www/wp-includes/shortcodes.php(325): jNewsticker_Bootstrap->shortcode(Array, '', 'newsticker')
#3 [internal function]: do_shortcode_tag(Array)
#4 /www/wp-includes/shortcodes.php(199): preg_replace_callback('/\\[(\\[?)(newsti...', 'do_shortcode_ta...', '[newsticker id=...')
#5 /www/wp-includes/class-wp-hook.php(286): do_shortcode('[newsticker id=...')
#6 /www/wp-includes/plugin.php(208): WP_Hook->apply_filters('[newsticker id=...', Array)
#7 /www/wp-content/themes/bigwig/framework/php/PeTheme/View/LayoutModule/PeThemeViewLayoutModule.php(82): apply_filters('the_content', '[newsticker id=...')
#8 /www/wp-content/themes/big in /www/wp-content/plugins/jnewsticker-for-wordpress/data_source.class.php on line 491

Do you guys have an update for this? 

Thanks,

Jacob

**Comment by ericnicolaas** [comment]
Hi Jacob, 

Just updated the readme and sent you an email, but just confirming here that we're not maintaining or supporting this anymore. Hope you're able to find a fix or a suitable alternative.

Cheers,
Eric

**Comment by jdknopp** [comment]
This is a result of order of operation changes between PHP5 and 7. Fix by adding curly braces on  line 491:
$this->$details['method']( $item_data )
becomes
$this->{$details['method']}( $item_data )
